// frontend/md_react/MermaidRenderer.jsx
/**
 * @fileoverview Mermaid图表渲染组件 - 渲染Mermaid语法的图表和流程图
 * 支持流程图、时序图、甘特图等多种图表类型，提供主题切换和错误处理
 * @author hhyufan
 * @version 1.4.0
 */

import React, { useEffect, useRef, useState } from 'react';
import { Alert, Skeleton } from 'antd';
import mermaid from 'mermaid';
import { useI18n } from '../hooks/useI18n';
import './MermaidRenderer.css';

mermaid.initialize({
    startOnLoad: false,
    theme: 'default',
    securityLevel: 'loose',
    fontFamily: 'JetBrains Mono, Consolas, Monaco, monospace',
    fontSize: 14,
    flowchart: {
        useMaxWidth: true,
        htmlLabels: true,
        curve: 'basis'
    },
    sequence: {
        diagramMarginX: 50,
        diagramMarginY: 10,
        actorMargin: 50,
        width: 150,
        height: 65,
        boxMargin: 10,
        boxTextMargin: 5,
        noteMargin: 10,
        messageMargin: 35,
        mirrorActors: true,
        bottomMarginAdj: 1,
        useMaxWidth: true,
        rightAngles: false,
        showSequenceNumbers: false
    },
    gantt: {
        titleTopMargin: 25,
        barHeight: 20,
        fontFamily: 'JetBrains Mono, Consolas, Monaco, monospace',
        fontSize: 11,
        fontWeight: 'normal',
        gridLineStartPadding: 35,
        bottomPadding: 25,
        leftPadding: 75,
        topPadding: 50,
        rightPadding: 25
    }
});

/**
 * Mermaid图表渲染组件
 * 根据提供的Mermaid代码渲染对应的图表，支持主题切换和错误处理
 * @param {Object} props - 组件属性
 * @param {string} props.code - Mermaid图表代码
 * @param {boolean} props.isDarkMode - 是否为暗色主题，默认为false
 * @returns {JSX.Element} Mermaid图表渲染组件
 */
const MermaidRenderer = ({ code, isDarkMode = false }) => {
    const { t } = useI18n();
    const elementRef = useRef(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [svgContent, setSvgContent] = useState('');

    useEffect(() => {
        if (!code) return;

        setLoading(true);
        setError(null);

        const timer = setTimeout(async () => {
            try {
                mermaid.initialize({
                    theme: isDarkMode ? 'dark' : 'default',
                    startOnLoad: false,
                    securityLevel: 'loose',
                    fontFamily: 'JetBrains Mono, Consolas, Monaco, monospace'
                });

                const id = `mermaid-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;

                const { svg } = await mermaid.render(id, code);
                setSvgContent(svg);
                setLoading(false);
            } catch (err) {
                setError(err.message || 'Failed to render Mermaid diagram');
                setLoading(false);
            }
        }, 500);

        return () => {
            clearTimeout(timer);
        };
    }, [code, isDarkMode]);

    if (loading) {
        return (
            <div
                className={`mermaid-container ${isDarkMode ? 'dark' : 'light'}`}
                style={{ padding: '16px' }}
            >
                <div className={`skeleton-wrapper ${isDarkMode ? 'dark' : 'light'}`}>
                    <Skeleton active paragraph={{ rows: 4 }} />
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="mermaid-container">
                <Alert
                    message={t('mermaid.renderFailed')}
                    description={error}
                    type="error"
                    showIcon
                    style={{
                        backgroundColor: isDarkMode ? '#21262d' : '#fff2f0',
                        borderColor: isDarkMode ? '#f85149' : '#ffccc7',
                        color: isDarkMode ? '#f85149' : '#ff4d4f'
                    }}
                />
            </div>
        );
    }

    return (
        <div
            className={`mermaid-container ${isDarkMode ? 'dark' : 'light'}`}
            ref={elementRef}
            dangerouslySetInnerHTML={{ __html: svgContent }}
            style={{
                textAlign: 'center',
                padding: '16px',
                backgroundColor: isDarkMode ? '#0d1117' : '#ffffff',
                borderRadius: '8px',
                border: `1px solid ${isDarkMode ? '#30363d' : '#e1e4e8'}`
            }}
        />
    );
};

export default MermaidRenderer;

// frontend/src/components/MermaidRenderer.vue
<template>
  <div
    v-if="loading"
    :class="`mermaid-container ${isDarkMode ? 'dark' : 'light'}`"
    style="padding: 16px"
  >
    <div :class="`skeleton-wrapper ${isDarkMode ? 'dark' : 'light'}`">
      <el-skeleton :rows="4" animated />
    </div>
  </div>

  <div v-else-if="error" class="mermaid-container">
    <el-alert
      :description="error"
      :show-icon="true"
      :style="{
        backgroundColor: isDarkMode ? '#21262d' : '#fff2f0',
        borderColor: isDarkMode ? '#f85149' : '#ffccc7',
        color: isDarkMode ? '#f85149' : '#ff4d4f',
      }"
      :title="t('mermaid.renderFailed')"
      type="error"
    />
  </div>

  <div
    v-else
    ref="elementRef"
    :class="`mermaid-container ${isDarkMode ? 'dark' : 'light'}`"
    :style="{
      textAlign: 'center',
      padding: '16px',
      backgroundColor: isDarkMode ? '#0d1117' : '#ffffff',
      borderRadius: '8px',
      border: `1px solid ${isDarkMode ? '#30363d' : '#e1e4e8'}`,
    }"
    v-html="svgContent"
  />
</template>

<script lang="ts" setup>
import { onMounted, ref, watch } from 'vue'
import mermaid from 'mermaid'
import { useI18n } from 'vue-i18n'

interface Props {
  code: string
  isDarkMode?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  isDarkMode: false,
})

const { t } = useI18n()
const elementRef = ref<HTMLElement>()
const loading = ref(true)
const error = ref<string | null>(null)
const svgContent = ref('')

// Initialize mermaid configuration
mermaid.initialize({
  startOnLoad: false,
  theme: 'default',
  securityLevel: 'loose',
  fontFamily: 'JetBrains Mono, Consolas, Monaco, monospace',
  fontSize: 14,
  flowchart: {
    useMaxWidth: true,
    htmlLabels: true,
    curve: 'basis',
  },
  sequence: {
    diagramMarginX: 50,
    diagramMarginY: 10,
    actorMargin: 50,
    width: 150,
    height: 65,
    boxMargin: 10,
    boxTextMargin: 5,
    noteMargin: 10,
    messageMargin: 35,
    mirrorActors: true,
    bottomMarginAdj: 1,
    useMaxWidth: true,
    rightAngles: false,
    showSequenceNumbers: false,
  },
  gantt: {
    titleTopMargin: 25,
    barHeight: 20,
    fontSize: 11,
    gridLineStartPadding: 35,
    leftPadding: 75,
    topPadding: 50,
    rightPadding: 25,
  },
})

const renderMermaid = async () => {
  if (!props.code) return

  loading.value = true
  error.value = null

  // Add delay to prevent immediate rendering
  setTimeout(async () => {
    try {
      // Update theme based on dark mode
      mermaid.initialize({
        theme: props.isDarkMode ? 'dark' : 'default',
        startOnLoad: false,
        securityLevel: 'loose',
        fontFamily: 'JetBrains Mono, Consolas, Monaco, monospace',
      })

      const id = `mermaid-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`
      const { svg } = await mermaid.render(id, props.code)
      svgContent.value = svg
      loading.value = false
    } catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to render Mermaid diagram'
      loading.value = false
    }
  }, 500)
}

// Watch for changes in code or dark mode
watch([() => props.code, () => props.isDarkMode], () => {
  renderMermaid()
})

onMounted(() => {
  renderMermaid()
})
</script>

<style scoped>
/* Mermaid 渲染器样式 */
.mermaid-container {
  width: 100%;
  overflow-x: auto;
  margin: 16px 0;
  padding: 1em;
}

.mermaid-container.dark svg {
  background-color: transparent;
}

/* 节点样式 */
.mermaid-container.dark .node rect,
.mermaid-container.dark .node circle,
.mermaid-container.dark .node ellipse,
.mermaid-container.dark .node polygon {
  fill: #21262d;
  stroke: #30363d;
  stroke-width: 2px;
}
/* 响应式设计 */
@media (max-width: 768px) {
  .mermaid-container {
    font-size: 12px;
  }
}

/* 滚动条样式 */
.mermaid-container::-webkit-scrollbar {
  height: 8px;
}

.mermaid-container::-webkit-scrollbar-track {
  background: transparent;
}

.mermaid-container::-webkit-scrollbar-thumb {
  background: #30363d;
}

.mermaid-container::-webkit-scrollbar-thumb:hover {
  background: #656c76;
}
</style>
